/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type { Provider, BaseWalletLocked, AbstractAddress } from "fuels";
import { Interface, Contract } from "fuels";
import type { ContractAbi, ContractAbiInterface } from "../ContractAbi";
const _abi = [
  {
    type: "function",
    name: "create_event",
    inputs: [
      {
        type: "u64",
        name: "capacity",
      },
      {
        type: "u64",
        name: "price",
      },
      {
        type: "str[10]",
        name: "eventName",
      },
    ],
    outputs: [
      {
        type: "struct Event",
        name: "",
        components: [
          {
            type: "u64",
            name: "uniqueId",
          },
          {
            type: "u64",
            name: "maxCapacity",
          },
          {
            type: "u64",
            name: "deposit",
          },
          {
            type: "enum Identity",
            name: "owner",
            components: [
              {
                type: "struct Address",
                name: "Address",
                components: [
                  {
                    type: "b256",
                    name: "value",
                  },
                ],
              },
              {
                type: "struct ContractId",
                name: "ContractId",
                components: [
                  {
                    type: "b256",
                    name: "value",
                  },
                ],
              },
            ],
          },
          {
            type: "str[10]",
            name: "name",
          },
          {
            type: "u64",
            name: "numOfRSVPs",
          },
        ],
      },
    ],
  },
  {
    type: "function",
    name: "rsvp",
    inputs: [
      {
        type: "u64",
        name: "eventId",
      },
    ],
    outputs: [
      {
        type: "struct Event",
        name: "",
        components: [
          {
            type: "u64",
            name: "uniqueId",
          },
          {
            type: "u64",
            name: "maxCapacity",
          },
          {
            type: "u64",
            name: "deposit",
          },
          {
            type: "enum Identity",
            name: "owner",
            components: [
              {
                type: "struct Address",
                name: "Address",
                components: [
                  {
                    type: "b256",
                    name: "value",
                  },
                ],
              },
              {
                type: "struct ContractId",
                name: "ContractId",
                components: [
                  {
                    type: "b256",
                    name: "value",
                  },
                ],
              },
            ],
          },
          {
            type: "str[10]",
            name: "name",
          },
          {
            type: "u64",
            name: "numOfRSVPs",
          },
        ],
      },
    ],
  },
];

export class ContractAbi__factory {
  static readonly abi = _abi;
  static createInterface(): ContractAbiInterface {
    return new Interface(_abi) as unknown as ContractAbiInterface;
  }
  static connect(
    id: string | AbstractAddress,
    walletOrProvider: BaseWalletLocked | Provider
  ): ContractAbi {
    return new Contract(id, _abi, walletOrProvider) as unknown as ContractAbi;
  }
}
